export { ChatView } from './components/chat-view';
export { useChatStore } from './store';
export {
  detectChatIntent,
  detectPlanApproval,
  extractConceptFromMessages,
  buildBriefFromProject,
  buildStoryboardScenes,
  buildCreativeWorkflowPlan,
  buildCreativeWorkflowPlanWithPrompts,
  BRAINSTORM_SYSTEM_PROMPT,
  isGreetingOrSmallTalk,
  wantsExplicitPlan,
  hasVideoConceptSignal,
  shouldPresentPlan,
  getConversationSuggestions,
  buildFallbackConversation,
  shouldPresentScript,
  detectScriptApproval,
  isSkipToWorkflow,
  wantsInfluencerStep,
  wantsBackgroundStep,
  wantsFramesStep,
  buildFallbackVideoScript,
  buildFallbackVideoScriptFromPlan,
  getScriptFromJson,
  extractSceneCountFromText,
  resolvePreferredSceneCount,
  clampScriptToSceneCount,
  type ChatIntent,
  type ScriptBuildInput,
  type PlanBuildOptions,
} from './lib/chat-handlers';
